### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [freezy/VisualPinball.Engine#264]
https://openupm.com/packages/org.visualpinball.engine.unity/?subPage=pipelines

Git tag: v0.0.1-preview.1
package.json: v0.0.1-preview.0

To fix: bump package.json and retag v0.0.1-preview.1

**Comment by freezy** [comment]
We have our own registry where tags and versions are set correctly.

**Comment by freezy** [comment]
Any way you can remove us from OpenUPM please?

**Comment by favoyang** [comment]
Hi @freezy,

I want to point out that the license GPL-3.0 License allows anyone who respects the license to redistribution the package. But we respect the author's demands, and your packages will be removed and blocked (to avoid future submission) within one hour.  

I can not find the registry mentioned in the README, perhaps something to add.

Just a friendly note, you may also want to double-check the version.
- the package.json of [the master branch](https://github.com/freezy/VisualPinball.Engine/blob/master/package.json): v0.0.1-preview.0
- the package.json of Git tag [v0.0.1-preview.1](https://github.com/freezy/VisualPinball.Engine/blob/v0.0.1-preview.1/package.json): v0.0.1-preview.0
- perhaps your CI bump the version and published a package, but forget to commit the changed package.json, which caused the issue.

I will update you when your package is removed from OpenUPM. Sorry for interrupting you.

**Comment by favoyang** [comment]
@freezy the package has been removed from OpenUPM. Your namespace `org.visualpinball` has been blocked in https://github.com/openupm/openupm/blob/master/data/blocked-scopes.yml. If you ever want to give OpenUPM a try, please remember to send PR to update that files first.

Thanks for your time.

**Comment by freezy** [comment]
@favoyang Thanks. We're in the middle of setting up CI to publish on merge. We wanted to avoid additional commits for each merge, so as you noticed we bump package.json before publishing. Our users will only use the package from the registry, and our devs have it locally where it's mutable and will be refreshed by Unity on any changes.

That said, going forward we will probably update package.json in the repo as well in order to stay coherent. If everything is in place you might get a PR with the blocked scoped removed.

Cheers!
