### ISSUE TITLE
Handle layers in editor

### ISSUE THREAD

**Issue by freezy** [freezy/VisualPinball.Engine#77]
VPX has 11 layers where elements can be rapidly hidden and shown in order to keep the view port in order. VPX 10.7 comes with an arbitrary number of layers, which can also be named, and displays a tree structure of all elements.

The tree structure we already have in the hierarchy, but handling layers in Unity would be nice too. AFAIK there isn't such a thing, so we could implement our own with a [custom editor](https://docs.unity3d.com/Manual/editor-EditorWindows.html).

**Comment by Vroonsh** [comment]
Maybe we could use the Tag & Layers editor from Unity

https://docs.unity3d.com/Manual/class-TagManager.html
https://docs.unity3d.com/Manual/Layers.html

We could create the existing 11 layers and affect objects at import stage then let the table designer add/rename them afterward.
Do we want to have a full retro compatibility , being able to read VPE tables from VPX ?

**Comment by freezy** [comment]
AFAIK the tags and layers play a role in the Unity rendering pipeline. This is just an editor help to rapidly toggle stuff while authoring. @rbxnk any other idea?

**Comment by rbxnk** [comment]
Yeah I'd recommend staying away from the built in tag and layer systems since they have other distinct meanings for the engine. Additionally (AFAIK) there's no way to modify the names and such in code, so the import would be slightly awkward anyway.

Assuming they're primarily used in VPX for organization and to able to hide and show arbitrary groups of items, why couldn't we just make use of the game object heirarchy? The importer could just place the objects under and empty GO with each layer's name, and then you could just toggle that one object to hide all the stuff underneath it. Moving things between layers would be a simple drag and drop.

I'm not 100% certain on this, but I'm pretty sure there's nothing about the existing systems that would prevent us from rearranging the items, as long as we keep the layer objects with identity transforms etc.

**Comment by freezy** [comment]
Yes, simply using the hierarchy was my first intuition as well. Here are my arguments against:

- For loading it would work well - however for saving it's probably a nightmare dealing with all the edge cases. Assuming level 2 is the layer level, what happens if a game element is directly on that level? Or if the users creates more than 11 layers?
- I really like the hierarchy we currently have, which is by game item type. If we add an intermediate layer, then separating by type doesn't make any sense anymore, so we would lose that feature.

It's also a usability thing. Layers are supposed to help organize the author's game items. If they are only usable if the author creates the hierarchy in a certain way, then it's probably not of much help. The author should be able to create whatever kind of hierarchy preferred, and VPE will then just grab everything below the root node when exporting (currently not the case though). I would see the layers more as an additional tool.

@Vroonsh if you're going to take this one, please assign yourself. Note that you'll need to add support for layer names to the data layer first, I haven't ported that yet. Two new BIFF attributes I think, and would prefer a first separate PR for this :)

**Comment by Vroonsh** [comment]
yup i'll take it.
Will firstly add the "LANR" Data support.

**Comment by freezy** [comment]
Fixed in #128.
